- .circleci/config.yml
- Makefile
This PR does a few things:
1. Creates a builder based on `functions-builder.toml` during testing. This file was previously untested.
2. Publishes `heroku/pack:18` and `heroku/pack:18-build` images automatically after successful testing.
3. Publishes `heroku/buildpacks:18` and `heroku/functions-buildpacks:18` images automatically after successful testing.
4. Drops use of `:nightly` tag, in favor of `:18` and `:latest` on `heroku/functions-buildpacks` for consistency with `heroku/buildpacks`.
> Automatically publish heroku/pack, heroku/buildpacks, and heroku/functions-buildpacks

- builder.toml
- buildpacks/install.sh
- functions-builder.toml
- go.mod
- go.sum
This upgrades to lifecycle `0.4.0` which introduces a breaking change as well uses the `api` key in `builder.toml`. This includes updates to the heroku buildpacks + shim to make sure it works.
> Update to lifecycle 0.4.0

- builder.toml
This adds the buildpack to image, but not any of the groups. We can't have it in the groups because it always passes. Instead, users must add `--buildpack heroku/jvm` to a command like `pack` to use it.
> Add heroku/jvm buildpack to builder image

- builder.toml
Upgrade lifecycle in `heroku/buildpacks:18` to 0.5.0, and fix the `heroku/jvm` URL
> Builder 0.5.0 and a fix

- .circleci/config.yml
Build, test, and publish the images we create on a nightly basis.  This will ensure the builder and CNB base images keep up to date with the base heroku:18 image.
> Nightly Build

- builder.toml
- functions-builder.toml
This supports build time env vars when using NPM, <https://github.com/heroku/nodejs-npm-buildpack/pull/14>
> update nodejs-npm-buildpack to 0.1.2

- builder.toml
- buildpacks/install.sh
The shim versions were a little rediculous, for example:
```
$ pack build myimage --no-pull
===> DETECTING
[detector] heroku/php      v0.0.5.0.2
[detector] heroku/procfile 0.3
```
This PR changes the following:
* Remove the `v` prefix
* Shorten the actual buildpack version to just one number (this is largely superficial and meant to bust caches so there's no need to use major minor)
New look:
```
$ pack build myimage --no-pull
===> DETECTING
[detector] heroku/php      0.0.5.2
[detector] heroku/procfile 0.3
```
> Fix the versions used for shims so it's more concise

- builder.toml
The "java buildpack" is now three buildpacks:
- heroku/jvm
- heroku/maven
- heroku/procfile
> replace heroku/java buildpack with composite buildpack order

- functions-builder.toml
This matches the `builder.toml`.
@jabrown85 this would mean you don't need to wait for https://github.com/heroku/java-buildpack/pull/9 but then we'd need to apply https://github.com/heroku/java-buildpack/pull/10 to `heroku/jvm` and `heroku/maven`.
> Update function-builder to use decomposed java buildpacks

- Dockerfile.run
…because it polutes the wkdir with bash scripts
> Don't create the heroku user with home at /workspace 

- builder.toml
- functions-builder.toml
Adds the yarn buildpack to both the functions-builder and builder files.
For the groups, the builders will detect for first yarn group, and then fall back on using npm.
> add yarn buildpacks and groups

- .circleci/config.yml
- builder.toml
- functions-builder.toml
This gets the CircleCI build running again. 
- The python and php classic buildpacks attempt to write to the buildpack's own directory. This is problematic in newer CNB versions, as that directory is read only. We're removing them from the build for now.
- Fixed a version number for the `nodejs-fn` buildpack
- Fixed a version number for the `procfile` buildpack
- Fixed a version number for the `node-function` buildpack
> Get the build running again

- builder.toml
- functions-builder.toml
Update to give builders up-to-date patch changes for Node buildpack.
Takes fix: https://github.com/heroku/nodejs-engine-buildpack/pull/36
> update nodejs-engine buildpack versions to 0.4.3

- functions-builder.toml
- Support for Secrets.get(secret).get(key) and Secrets.getValue(secret,key)
- Reduced startup/secret-checking logging
> Bump nodejs-sf-fx-buildback to 1.1.2

- Makefile
- builder.toml
- buildpacks/install.sh
- functions-builder.toml
Reverts heroku/pack-images#78
We need to update `pack 0.9.0' in [heroku/builder](https://github.com/heroku/builder) first as seen in buildpacks/pack#509.
> Revert "upgrade to lifecycle 0.7.2. Some perf improvements to launcher."

- functions-builder.toml
This PR includes an update to the latest version (v0.2.0) of the `nodejs-npm-buildpack`. 
https://github.com/heroku/nodejs-npm-buildpack/pull/18
> update nodejs-npm-buildpack to 0.2.0

- functions-builder.toml
The `heroku/evergreen-node-system-function` buildpack is no longer neccessary since it was merged with the Salesforce middleware function
https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/26
Because of this, the `salesforce/nodejs-fn` buildpack can no longer be `optional`
> combine system and salesforce functions into single buildpack

- functions-builder.toml
This version update to the salesforce nodejs buildpack removes the requirement that all user functions have `@salesforce/salesforce-sdk` as a dependency in their `package.json` in order to pass the `detect` phase.
> update version for salesforce-nodejs buildpack

- functions-builder.toml
This will allow the `DEBUG_PORT` to be used and automatically enabled when using `evergreen:function:start`
> chore: bump nodejs-sf-fx-buildpack to v1.4.3

- builder.toml
lifecycle `0.7.5` includes a fix for https://github.com/buildpacks/lifecycle/issues/290 which some users are experiencing when using our builder image to do a `pack build --publish` and seeing the following error message:
```
ERROR: failed to new app image: /root/.docker/config.json: stat /root/.docker/config.json: permission denied
```
> upgrade to lifecycle 0.7.5

- .circleci/config.yml
- Dockerfile.build
- Dockerfile.riff.build
- Makefile
- functions-builder.toml
**NOTE: This PR has a dependency on https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/tag/v1.5.0
This PR is responsible for removing our dependency on our forked `heroku/node-function` buildpack/invoker, and instead will allow us to use the upstream version of riff.  
Additionally, short-term changes were made to satisfy the `RIFF=1` requirement in order for the `detect` phase to pass while building a function.  Having the ENV var stored in `/plaform` allows us to truly hide it from the user, and will make the removal process seamless.
> replace forked heroku/node-function buildpack with riff

- .circleci/config.yml
- Dockerfile.build
- Dockerfile.ci
- Makefile
- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
Riff is now split into multiple buildpacks instead of including the streaming adapter as a dependency. Riff also no longer requires `RIFF=1` to pass detection. Requiring the invoker buildpack is enough. The new requirement is in the sf-fx buildpack version bump.
I also updated pack builder image to ensure CI supports building the builder with the grc image references.
Example function being built with the updated builder. You can see the streaming adapter version is updated and that we have the new adapter buildpack.
All this is for [this work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008PK6fIAG/view) to support errors returned as JSON in failure states. Contributed that patch [here](https://github.com/projectriff/streaming-http-adapter/pull/56) and it was cut …
> Update to latest version of riff

- Makefile
- spring-boot-builder.toml
This builder works with the Spring-Boot plugins for [Gradle](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#build-image) and [Maven](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/reference/html/#build-image).
```
$ ./gradlew bootBuildImage --builder heroku/spring-boot-buildpacks  
```
> Add a spring-boot builder image

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
* sf-fx-sdk-nodejs buildpack 1.5.7 Includes latest @salesforce/salesforce-sdk version 1.3.0
* https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/tag/v1.5.7
* https://github.com/forcedotcom/sf-fx-sdk-nodejs/releases/tag/v1.3.0
> Bump nodejs-sf-fx-buildback to new 1.5.7 release (try #3)

- builder.toml
- buildpacks/evergreen_fn/buildpack.toml
- buildpacks/heroku_nodejs/buildpack.toml
- functions-builder.toml
Upgrades `nodejs-engine` to `0.4.4` and `nodejs-npm` to `0.2.0`.
Changes in these upgrades here:
- Node.js Engine: https://github.com/heroku/nodejs-engine-buildpack/blob/master/CHANGELOG.md#044-2020-03-25
- Node.js NPM: https://github.com/heroku/nodejs-npm-buildpack/blob/master/CHANGELOG.md#020-2020-05-19
> upgrade engine and npm buildpacks to 0.4.4 and 0.2.0 across all builders

- .circleci/config.yml
- builder.toml
- buildpacks/heroku_nodejs/buildpack.toml
Adds TypeScript buildpack from release v0.0.2. For now, the buildpack is only available in the Heroku meta buildpack.
This pull request also includes an added test in CI. The getting started guide (https://github.com/danielleadams/typescript-getting-started) is being reviewed by Salesforce OSS, so it will be able to use the same Job once the repo gets approved.
As we move towards creating a great Node experience for JavaScript developers, we want to make sure that the TypeScript experience is just as good. By adding supporting a TS buildpack, we can make data and feedback-based enhancements to the DX for developers using CNBs.
> add typescript buildpack to heroku/nodejs builder

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
* Functions Middleware adds support for Cloudevents 1.0 format with `*context` values in extensions attributes rather than mixed in with function payload `data`
> Bump nodejs-sf-fx-buildback to new 1.6.0 release

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
Reverts heroku/pack-images#108. With the latest [nodejs-sf-fx-buildpack](forcedotcom/nodejs-sf-fx-buildpack) (1.6.0), canaries are failing. Lets rollback to the latest working code.
Slack conversation here: https://heroku.slack.com/archives/CQ20PPUR4/p1595346419347100
Failures here:
- https://circleci.com/workflow-run/00d8b604-719b-45f1-a605-84aa12d2c0ae?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
- https://circleci.com/workflow-run/7f786359-077a-4983-8391-4936d1051bfb?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
- https://circleci.com/workflow-run/4577c860-b2c9-4096-b285-7fd0198d86e2?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
> Revert "Bump nodejs-sf-fx-buildback to new 1.6.0 release"

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
* Re-adding support for CloudEvents 1.0 format with separation of payload `data` from auth/invocation context information in `sfcontext` and `sffncontext` attributes
* Handle 0.2 structured json format sent from Core API 48.0 (Summer '20 release)
* Handle 0.3 HTTP binary and structured json formats sent from `sfdx evergreen:function:invoke`.
* Handle 1.0 structured json format sent from Core API 50.0+ (Fall '20 release, currently under test).
* Fixes/tests noted here: https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/48
> Bump nodejs-sf-fx-buildback to 1.6.1 release (CloudEvent 1.0 support)

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
Includes new SDK version compatibility functionality from https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pulls/50 and https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pulls/51.
[GUS Item](https://gus.lightning.force.com/a07B0000008NmGzIAK)
> Update forcedotcom/nodejs-sf-fx-buildpack to v1.8.0

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
Update to latest nodejs sf fx buildpack:
* Fixes issue with wrong `content-length` header for async requests
* Update to cloudevents 3.1.0
> Update forcedotcom/nodejs-sf-fx-buildpack to v1.9.0

- buildpacks/evergreen_fn/buildpack.toml
- functions-builder.toml
Bugfix in nodejs-sf-fx-buildpack:
* Fix middleware error `Cannot use 'in' operator to search for 'data' in <string>`
> Update forcedotcom/nodejs-sf-fx-buildpack to v1.9.1

- .circleci/config.yml
We previously leaned on https://github.com/heroku/evergreen-hilltop-theatre-terraform as canaries for validating function builders. That repository is not seeing updates as event invocation is scheduled for later delivery. We should use canaries that are actively being updated and tested instead.
> Use newer canaries in CI

- functions-builder.toml
We can't currently build Java functions for a variety of reasons. Some highlights are that https://github.com/heroku/java-function-buildpack is behind on lifecycle version, and it's far behind it's upstream Riff counterpart. It'll be a sizable effort to get the existing buildpack(s) back in working order, and I'm not sure it's worth the effort given there is a new implementation on the horizon.
> Remove support for Java functions

- .circleci/config.yml
The `typescript-getting-started` guide has passed OSS and security review, so we can run the test the same as the other getting started guides.
> Use Heroku TS Getting Started Guide

- .circleci/config.yml
The CI configuration used cache, which was relying on the repo SHA to key cache usage from. This is not what we want. We want the nightly job to build fresh images nightly as upstream bits may have changed (base images, cnb-develop, etc.). Using job-local storage instead of cache simplifies the job and will probably speed things up a bit as well.
> fix: circleci cache configuration

- builder.toml
- buildpacks/evergreen_fn/buildpack.toml
This brings in the changes from forcedotcom/nodejs-sf-fx-buildpack/pull/63.
> chore: Bump nodejs-sf-fx-buildpack to v2.0.1

- .circleci/config.yml
- Dockerfile.build
- Dockerfile.run
- Makefile
- README.md
The first step for Heroku-20 support is to start building and publishing the `heroku/pack:20` and `heroku/pack:20-build` stack images.
Once these are available, CNB authors will be able to test their buildpacks against the new stack, and in a later PR we'll start publishing the `heroku/buildpacks:20` builder with the updated CNBs.
For more on the remaining Heroku-20 tasks, see:
https://salesforce.quip.com/LbhlAFPd1rvR#fCAACA6FA2X
Closes [W-8270099](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008hLTWIA2/view).
> Start building heroku/pack:20 and heroku/pack:20-build

- builder-18.toml
- buildpacks/evergreen_fn/buildpack.toml
- buildpacks/heroku_nodejs/buildpack.toml
- Add profile.d script to set WEB_CONCURRENCY to app ([#53](https://github.com/heroku/nodejs-engine-buildpack/pull/53))
- Set NODE_ENV to production at runtime ([#54](https://github.com/heroku/nodejs-engine-buildpack/pull/54))
- Set NODE_ENV to production or set variable in build environment ([#55](https://github.com/heroku/nodejs-engine-buildpack/pull/55))
- set custom tsconfig or use default `tsconfig.json` ([#10](https://github.com/heroku/nodejs-typescript-buildpack/pull/10))
> upgrade nodejs-engine buildpack to v0.6.0 and nodejs-typescript buildpack to v0.1.0

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
- buildpacks/heroku_nodejs/buildpack.toml
- Add support for heroku-20 ([#60](https://github.com/heroku/nodejs-engine-buildpack/pull/60))
- Remove jq installation ([#57](https://github.com/heroku/nodejs-engine-buildpack/pull/57))
- Make `NODE_ENV` variables overrides ([#61](https://github.com/heroku/nodejs-engine-buildpack/pull/61))
- Add heroku-20 to supported stacks ([#40](https://github.com/heroku/nodejs-npm-buildpack/pull/40))
- Add support for heroku-20 and bionic stacks ([#4](https://github.com/heroku/nodejs-yarn-buildpack/pull/4))
- Add heroku-20 support and stack-specific tests ([#13](https://github.com/heroku/nodejs-typescript-buildpack/pull/13))
> Updating Node.js buildpacks for Heroku-20 support

- builder-18.toml
- builder-20.toml
- spring-boot-builder-18.toml
- spring-boot-builder-20.toml
Update buildpack URIs for several builders. The new versions are:
heroku/maven (heroku/java): v68
heroku/jvm: v111
> Update java buildpacks

- .circleci/config.yml
- Dockerfile.ci
- Makefile
- builder-18.toml
- builder-20.toml
- spring-boot-builder-18.toml
- spring-boot-builder-20.toml
This PR updates pack to 0.15.0 and lifecycle to 0.9.3.
It also drops the custom CI image in favor of inline pack installation, since that workflow was manual and completely undocumented.
> Update Pack to 0.15.0, lifecycle to 0.9.3

- builder-18.toml
- buildpacks/evergreen_fn/buildpack.toml
This brings in the update from https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/65.
> Update nodejs-fn buildpack to 2.0.2

- builder-18.toml
- buildpacks/evergreen_fn/buildpack.toml
The previous sf-fx-buildpack update prevents functions from starting correctly. See https://heroku.slack.com/archives/CHYJ2J0QL/p1608140902106100.
Reverts heroku/pack-images#142
> Revert "Update to node-fn 2.0.3"

- .circleci/config.yml
- Makefile
- builder-18.toml
- builder-20.toml
- spring-boot-builder-18.toml
- spring-boot-builder-20.toml
- Update to lifecycle 0.10.1 on all our builders
- Update to pack 0.15.1 in circle ci and update cli usage
- Update Makefile to successfully build with updated version of pack while only pulling images not on the local machine
- Updated builder image references to use docker:// as suggested by pack upon failure
> Bump lifecycle version to 0.10.1

- .circleci/config.yml
We've had issues where buildpack upgrades create containers successfully, but then the container immediately crashes. A small smoke test after each getting-started guide should ensure the images at least remain running and prevent some bad releases.
> Ensure getting-started guide containers start successfully

- builder-18.toml
- buildpacks/evergreen_fn/buildpack.toml
This brings in the changes from https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/67. This should allow functions to be built from nested source code directories.
> Upgrade nodejs-sf-fx buildpack to 2.0.4

- .circleci/config.yml
- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
- Bumped versions of evergreen_fn metabuildpack to versions compatible with `heroku-20` and `heroku-18` stacks.
- Added canary tests to workflow for publishling `heroku/buildpacks:20` in CircleCI
Signed-off-by: Jesse Brown <jabrown85@gmail.com>
> Add evergreen_fn buildpacks to heroku/buildpacks:20

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
Bump buildpack to bring in proper cache busting for stack changes.
Ref: https://github.com/forcedotcom/nodejs-sf-fx-buildpack/pull/70
> Bump salesforce/nodejs-fn to 2.0.6

- .circleci/config.yml
AWS allows 1 unauthenticated pull per IP per second. This will hopefully throttle the pulls enough to have passing builds on the nightlys. There are 2 API endpoints that are being hit, BatchGetImage and GetDownloadUrlForLayer, that need to pass for a successful pull.
> runs create-builder 5 times before failing

- builder-18.toml
- builder-20.toml
This description is used by `pack` and other tooling. It is described in an upcoming RFC [here](https://github.com/buildpacks/spec/pull/193/files#diff-f42ff52873ec233ac5f2927cbd0d49bdb8f8c88e36198dadd42c73e2fef72f7dR77-R81).
> Added builder descriptions

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
Updates the Node.js buildpacks and removes the referenced buildpacks that are no longer needed in favor of the meta buildpack. Also upgrades the `procfile-cnb` versions for all the referenced buildpack groups in the builders.
> update heroku/nodejs versions

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
With riff no longer active, let's switch to our own forks.
The updated buildpacks exist in https://hub.docker.com/orgs/heroku/repositories.
> Update node and streaming buildpacks

- .circleci/config.yml
Push produced images to another registry in addition to dockerhub.
Blockers:
> Push produced images to another registry in addition to dockerhub.

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Default version for **OpenJDK 7** is now `1.7.0_302`
* Default version for **OpenJDK 8** is now `1.8.0_292`
* Default version for **OpenJDK 11** is now `11.0.11`
* Default version for **OpenJDK 13** is now `13.0.7`
* Default version for **OpenJDK 15** is now `15.0.3`
* Default version for **OpenJDK 16** is now `16.0.1`
* Upgraded `heroku/jvm` to `0.1.6`
* Fixed `licenses` in `buildpack.toml`
* Upgraded `heroku/jvm-function-invoker` to `0.2.6`
* Upgraded `heroku/jvm` to `0.1.6`
> Update JVM buildpacks

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Switch from the Riff based invoker buildpacks to `heroku/nodejs-function` ([#48](https://github.com/heroku/buildpacks-node/pull/48))
> Update heroku/nodejs-function to 0.5.0

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/nodejs-function-invoker` to `0.1.1`
* Run check for "main" key and file in package.json ([#52](https://github.com/heroku/buildpacks-nodejs/pull/52))
* Support for newer versions of the function runtime
> Update heroku/nodejs-function buildpack

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/nodejs-function-invoker` to `0.1.2`
- Remote debugging is now enabled when the `DEBUG_PORT` environment variable is set ([#59](https://github.com/heroku/buildpacks-nodejs/pull/59))
- The `web` process is now marked as the default process type ([#60](https://github.com/heroku/buildpacks-nodejs/pull/60))
- The function runtime download is now cleaned up after installation ([#57](https://github.com/heroku/buildpacks-nodejs/pull/57))
> Update heroku/nodejs-function to 0.5.2

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/nodejs-function-invoker` to `0.1.3`
- Fixed `NODE_OPTIONS` unbound variable error when using `DEBUG_PORT` ([#63](https://github.com/heroku/buildpacks-nodejs/pull/63))
Refs GUS-W-9260143.
> Update heroku/nodejs-function to 0.5.3

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/jvm-function-invoker` to `0.2.8`
* `SF_FX_REMOTE_DEBUG` was renamed to `DEBUG_PORT` and also species the port on with the JDWP agent will listen on.
* Updated function runtime to `0.2.1`
* Update `bin/detect` to check for `type=function`.
> Update heroku/java-function to 0.3.9

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/jvm-function-invoker` to `0.2.10`
* Updated function runtime to `0.2.3`
> Update heroku/java-function to 0.3.11

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/jvm-function-invoker` to `0.2.11`
* Updated function runtime to `0.2.4`
> Update heroku/java-function to 0.3.12

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/nodejs-typescript` to `0.2.3`
* Upgraded `heroku/nodejs-npm` to `0.4.4`
* Upgraded `heroku/nodejs-engine` to `0.7.4`
* Upgraded `heroku/nodejs-typescript` to `0.2.3`
* Upgraded `heroku/nodejs-yarn` to `0.1.4`
* Upgraded `heroku/nodejs-npm` to `0.4.4`
* Upgraded `heroku/nodejs-engine` to `0.7.4`
The above changes bring in these additional changes...
- Clear cache when node version changes ([#40](https://github.com/heroku/buildpacks-node/pull/40))
- Clear cache when node version changes ([#40](https://github.com/heroku/buildpacks-node/pull/40))
- Clear cache when node version changes ([#40](https://github.com/heroku/buildpacks-node/pull/40))
- Change node engine version from 12 to 14 ([#40](https://github.com/heroku/buildpacks-node/pull/40))
- Clear cache when node …
> Update heroku/nodejs-function to 0.5.7 and heroku/nodejs to 0.3.5

- builder-18.toml
- builder-20.toml
* Upgraded `heroku/nodejs-yarn` to `0.1.5`
- Empty cache builds no longer fail with a `PREV_NODE_VERSION ` unbound variable error ([#86](https://github.com/heroku/buildpacks-node/pull/86))
Refs GUS-W-9481665.
> Update heroku/nodejs to 0.3.6

- builder-18.toml
- builder-20.toml
- spring-boot-builder-18.toml
- spring-boot-builder-20.toml
https://github.com/buildpacks/lifecycle/releases/tag/v0.11.4
https://github.com/buildpacks/lifecycle/compare/v0.11.3...v0.11.4
Of note, this includes a fix for correctly outputting the logs when a buildpack's build plan fails to parse.
Fixes GUS-W-9666164.
> Update lifecycle to 0.11.4

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
Shas from:
https://github.com/buildpacks/registry-index/blob/dbd48061c39e3d32e7a309303b179aed9dc5a2db/no/de/heroku_nodejs-function#L11
Closes GUS-W-9501671.
> Update heroku/nodejs-function to 0.5.9

- builder-18.toml
- builder-20.toml
These buildpacks are already transitive dependencies of `heroku/java` ([manifest](https://github.com/heroku/buildpacks-jvm/blob/270f75993d0173b1184535df73f6df440e6ea009/meta-buildpacks/java/package.toml)), and are not specified separately in the detection order.
Removing them does not stop someone from using those buildpacks individually (they will still be in the final builder image), but reduces the number of image URLs that must be updated each time a release occurs.
This came up in:
https://github.com/heroku/pack-images/pull/187#pullrequestreview-717771917
Fixes GUS-W-9672375.
> Remove redundant JVM buildpack dependencies

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
* Upgraded `heroku/jvm` to `0.1.7`
* Upgraded `heroku/jvm-function-invoker` to `0.4.0`
* Upgraded `heroku/jvm` to `0.1.7`
* Upgraded `heroku/maven` to `0.2.4`
* Upgraded `heroku/jvm-function-invoker` to `0.3.0`
---
The above changes bring in these additional changes...
* Default version for **OpenJDK 7** is now `1.7.0_312`
* Default version for **OpenJDK 8** is now `1.8.0_302`
* Default version for **OpenJDK 11** is now `11.0.12`
* Default version for **OpenJDK 13** is now `13.0.8`
* Default version for **OpenJDK 15** is now `15.0.4`
* Default version for **OpenJDK 16** is now `16.0.2`
* Revert all changes from `0.3.0`
* Updated function runtime to `1.0.0` again
* Changed implementation to Rust
* Updated function runtime to `1.0.0`
* Loosen stack requirements allowing any linux distro use …
> Update heroku/java to 0.3.9 and heroku/java-function to 0.3.14

- .circleci/config.yml
The Circle CI Docker images under the `circleci` namespace are their legacy images. The newest images are provided under the `cimg` Docker Hub namespace:
https://circleci.com/docs/2.0/circleci-images/
In addition, none of the Circle CI jobs actually use Go, so we can use the minimal base image instead of the Golang 1.15 variant which will stop being updated once Golang 1.15 is EOL.
See:
https://circleci.com/developer/images/image/cimg/base
Fixes GUS-W-9687767.
> Switch to the newer cimg/base Circle CI Docker image

- .circleci/config.yml
https://github.com/buildpacks/pack/releases/tag/v0.16.0
https://github.com/buildpacks/pack/releases/tag/v0.17.0
https://github.com/buildpacks/pack/releases/tag/v0.18.0
https://github.com/buildpacks/pack/releases/tag/v0.18.1
https://github.com/buildpacks/pack/releases/tag/v0.19.0
https://github.com/buildpacks/pack/releases/tag/v0.20.0
https://github.com/buildpacks/pack/compare/v0.15.1...v0.20.0
Fixes GUS-W-9683933.
> Update Pack CLI from 0.15.1 to 0.20.0

- builder-18.toml
- builder-20.toml
- buildpacks/evergreen_fn/buildpack.toml
Changelog:
* Upgraded `heroku/maven` to `0.2.5`
* Upgraded `heroku/jvm-function-invoker` to `0.5.0`
* Upgraded `heroku/maven` to `0.2.5`
---
The above changes bring in these additional changes...
* Changed implementation to Rust (relanded with upgrade to libcnb `0.1.3`)
* Ensures `mvnw` is executable
Closes GUS-W-9731821.
> Update heroku/java to 0.3.10 and heroku/java-function to 0.3.15

- README.md
Since all of the other entries had Heroku-18 and Heroku-20 variants apart from the builder entry.
> Add heroku/buildpacks:20 to the README

- .circleci/config.yml
There were a few deficiencies in the Circle Job that are being corrected here:
- We weren't testing the NodeJS or Typescript guide on heroku-20. 
- We weren't gating the heroku-20 releases on NodeJS or Typescript builds
- We weren't gating the heroku-18 releases on Typescript builds
[GUS Item](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07AH000000Ow0xYAC)
> Include node-js-20 and typescript-20 in the test matrix

- builder-18.toml
- builder-20.toml
This brings in the latest heroku/nodejs-function buildpack, which includes support for JavaScript Modules / ESM in Salesforce Functions.
More on that is here: https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/99
Here's the buildpack release this PR is referencing: https://github.com/buildpacks/registry-index/issues/1734
> Update heroku/nodejs-function buildpack to 0.6.0

- builder-18.toml
- builder-20.toml
Update [runtime](https://github.com/forcedotcom/sf-fx-runtime-nodejs) to [0.5.2](https://github.com/forcedotcom/sf-fx-runtime-nodejs/releases/tag/v0.5.2).
Changes:
- Handle malformed/missing cloud event salesforce extension ([#141](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/141))
- Update package name to @heroku/sf-fx-runtime-nodejs ([#139](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/139))
- Automatically expand ReferenceIDs with `.toApiString()` ([#133](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/133))
- Add unit testing for src/index.ts ([#118](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/118))
- Utilize @salesforce/core for logging with logfmt ([#119](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/119))
> release new nodejs function versions

- builder-18.toml
- builder-20.toml
This updates the heroku/node-function buildpack to 0.6.2, which will include the changes from https://github.com/heroku/buildpacks-nodejs/pull/122.
This will be a significant, but hopefully backwards compatible change.
**DO NOT MERGE UNTIL AFTER DREAMFORCE DEPLOY MORATORIUM**
GUS-W-9928321
GUS-W-9908872
GUS-W-9840764
> Update heroku/node-function to 0.6.2

- builder-18.toml
- builder-20.toml
[Release for java-function to v0.3.20](https://github.com/heroku/buildpacks-jvm/actions/runs/1287131339)
[W-9950528](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000As3fyYAB)
> Update heroku/java-function to v0.3.20

- .circleci/config.yml
- Makefile
Makes `heroku/buildpacks:latest` be tagged from `heroku/buildpacks:20` rather than `heroku/buildpacks:18`, since the default and latest stack is Heroku-20.
This is a no-op for Kodon, since it pins to a specific builder tag, rather than latest.
> Use `heroku/buildpacks:20` as `heroku/buildpacks:latest`

- builder-18.toml
- builder-20.toml
This bumps the nodejs-function buildpack to the latest release. There are only minor changes described here: https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/266.
GUS-W-10379120
> Bump nodejs-function to 0.6.10

- builder-18.toml
- builder-20.toml
* Upgraded `heroku/jvm-function-invoker` to `0.6.1`
* Switch to BSD 3-Clause License
* Upgrade to `libcnb` version `0.4.0`
* Updated function runtime to `1.0.5`
> Update heroku/java-function to 0.3.25

- builder-18.toml
- builder-20.toml
This updates the `heroku/nodejs` and `heroku/nodejs-function` buildpacks and effectively removes the `heroku/nodejs-typescript` buildpack from the builder. TypeScript is still supported via `heroku/nodejs-yarn` and `heroku/nodejs-npm` buildpacks. See https://github.com/heroku/buildpacks-nodejs/pull/178 for more context.
GUS-W-10455655
> Bump heroku/nodejs and heroku/nodejs-function

- builder-18.toml
- builder-20.toml
This updates both heroku/nodejs and heroku/nodejs-function to versions that include the fix described in https://github.com/heroku/buildpacks-nodejs/pull/186.
GUS-W-10034673
> Update node buildpacks to fix `tsc` issue

- builder-18.toml
- builder-20.toml
This release is based on a classic Heroku buildpack via [cnb-shim](https://github.com/heroku/cnb-shim). The changelog for that release can be found here: https://github.com/heroku/heroku-buildpack-scala/blob/main/CHANGELOG.md#v92
Switch to BSD 3-Clause License
> Update heroku/scala to 0.0.92

- builder-18.toml
- builder-20.toml
This updates heroku/nodejs-function to 0.7.2. It primarily adds support for `com.salesforce.salesforce-api-version` in `project.toml`, as described in https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/276.
[W-10474584](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000htVsBYAU)
> Update heroku/node-function to 0.7.2

- builder-18.toml
- builder-20.toml
This brings in heroku/nodejs-function 0.7.3. The notable change is https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/294.
GUS-W-10728741
> Update nodejs-function to 0.7.3

- builder-18.toml
- builder-20.toml
* Upgraded `heroku/jvm` to `0.1.14`
* Upgraded `heroku/maven` to `0.2.6`
* Upgraded `heroku/jvm` to `0.1.14`
* Upgraded `heroku/maven` to `0.2.6`
* Default version for **OpenJDK 11** is now `11.0.14.1`
* JDK overlays (using the `.jdk-overlay` directory) are now properly applied
* Switch to BSD 3-Clause License
* Applications that use Spring Boot are now properly detected even if their dependency to Spring Boot is transitive
> Bump `heroku/java` to `0.3.15`, `heroku/java-function` to `0.3.28`

- builder-18.toml
- builder-20.toml
Brings in the changes from https://github.com/heroku/buildpacks-nodejs/pull/184.
[GUS-W-10729118](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000qW9v8YAC)
> Update node buildpacks to nodejs-engine with libcnb

- builder-18.toml
- builder-20.toml
Upgraded `heroku/jvm` to `0.1.15`
Upgraded `heroku/maven` to `1.0.0`
Upgraded `heroku/jvm` to `0.1.15`
Upgraded `heroku/maven` to `1.0.0`
- Added support for Java 18
- Re-implement buildpack using [libcnb.rs](https://github.com/Malax/libcnb.rs)
- Source and Javadoc JAR files are no longer considered when determining the default web process.
> Update heroku/java and heroku/java-function buildpacks

- .circleci/config.yml
- builder-18.toml
- builder-20.toml
Our builders' dependencies are slightly out of date. This brings them current again.
[W-10708989](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000ozUkOYAU)
> Update pack to 0.24.1 and lifecycle to 0.13.5

- builder-18.toml
- builder-20.toml
This brings in the latest node buildpacks, and the following notable changes:
- https://github.com/heroku/buildpacks-nodejs/pull/225
- https://github.com/heroku/buildpacks-nodejs/pull/224
- https://github.com/heroku/buildpacks-nodejs/pull/201
[W-10915212](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000tsBWkYAM)
[W-10934205](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000u3znWYAQ)
> Update to latest node buildpacks

- builder-18.toml
- builder-20.toml
Version 1.0.0 of `heroku/procfile` can cause build failures on older versions of `pack`. More details here: https://github.com/heroku/procfile-cnb/pull/55
[W-10475648](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000hwHhMYAU)
> Bump heroku/procfile to 1.0.1

- .circleci/config.yml
- Makefile
- README.md
- builder-22.toml
This introduces  build, run, and builder images and automation based on the `heroku:22` stack image. This will make it possible to run CNB builds on the new `heroku-22` stack. 
`heroku/buildpacks:22` is in development and will start out very basic, with only buildpacks known to be working on `heroku-22` included. Other language buildpacks will be added as they gain support for `heroku-22`.
[W-10345122](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000ZZE8oYAH)
> Add heroku:22 images and automation

- README.md
Previously the `Base` column used a notation that looked like a tag name (due to the colon), but wasn't a valid tag. 
I've also added links to the stack-images repository, so it's easier for users to report issues with the underlying image to the correct repository.
> Update base image tag names in README

- builder-18.toml
- builder-20.toml
* Re-implement buildpack using [libcnb.rs](https://github.com/Malax/libcnb.rs) ([#272](https://github.com/heroku/buildpacks-jvm/pull/272))
* Remove support for GPG signed OpenJDK binaries. This feature wasn't used and will be replaced by a unified solution across Heroku buildpacks. ([#272](https://github.com/heroku/buildpacks-jvm/pull/272))
* Remove support for the `JDK_BASE_URL` environment variable. It was deprecated in Jan 2021 and was slated for removal Oct 2021. ([#272](https://github.com/heroku/buildpacks-jvm/pull/272))
* Remove support for the `JVM_BUILDPACK_ASSETS_BASE_URL` environment variable. ([#272](https://github.com/heroku/buildpacks-jvm/pull/272))
* Remove legacy debugging scripts: `with_jmap`, `with_jmap_and_jstack`, `with_jmap_and_jstack_java`, `with_jmap_java`, …
> JVM Buildpack Updates Q2 2022

- .circleci/config.yml
`pack create-builder` has been deprecated and emits warning messages in logs: https://app.circleci.com/pipelines/github/heroku/pack-images/1756/workflows/b575ece4-b9a3-4b47-93c2-8b69d472c3f2/jobs/36051?invite=true#step-108-10
> Use pack's "builder create" instead of "create-builder"

- builder-18.toml
- builder-20.toml
- builder-22.toml
This updates to the latest Node buildpacks, which includes node-18 capable buildpacks.
[GUS](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000xcm9BYAQ)
> Update to buildpacks with Node 18

- .circleci/config.yml
The default branch has been updated. This ensures our CI config matches.
Slack Thread: https://heroku.slack.com/archives/C02GZCPPV38/p1654259722803159
> Update default branch to main

- .circleci/config.yml
Due to a few changes in #251 to the CircleCI job, publishing builder images is failing. We need to tag an image before we can push it.
> Fix broken CircleCI pushes

- builder-22/builder.toml
Explicitly listing the Procfile CNB is only required for shimmed CNBs, since the native CNBs list it in their meta-buildpack.
As such this `[[buildpacks]]` asset entry is not required, since the procfile buildpack is not listed in the top-level `[[order]]` definition.
GUS-W-11263169.
> Remove unused Procfile CNB entry from `heroku/builder:22`

- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
`heroku/scala` was previously explicitly shimmed and released to the CNB registry as an OCI image. To align with other Heroku supported languages, the CNB shim webservice is now used instead.
> Use CNB shim webservice for heroku/scala

- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Since we don't properly manage this version anyway and to align with `heroku/builder:22`, this PR changes the CNB version of all shimmed buildpacks to `0.0.0`.
> Use version `0.0.0` for shimmed buildpacks

- .circleci/config.yml
Since:
- The retry handling is broken, such that if the command fails after three retries, then the exit code is obscured and the CI run continues to the next step. This causes a confusing error message that's shown instead of the actual error.
- In the case of legitimate failures, the retries prolong the time until the CI result shows the failure.
- The builder creation step is pretty reliable now (I've inspected several dozen invocations and didn't see any failures).
- If we start seeing intermittency in the future, I would rather know about it so we can improve reliability for everyone, rather than cover it up via retries.
GUS-W-11263169.
> Remove retrying of `pack builder create`

- .circleci/config.yml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
`heroku/java` previously supported Gradle by mixing in the shimmed `heroku/gradle` buildpack. When we decided to make a clean cut and not have shimmed buildpacks in the CNB repository, support for Gradle in `heroku/java` was dropped.
This is obviously a major breaking change and this PR reinstates Gradle support by mirroring the order definition that was previously in `heroku/java`. This is not a complete fix since users that explicitly used `heroku/java` (i.e. `--buildpack heroku/java` with `pack`) will still get detection failures for Gradle. However, using the builder without explicit buildpacks will work fine for Gradle projects.
Closes GUS-W-11298364
> Reinstate Gradle support for `heroku/buildpacks:{18,20}`

- README.md
Since Heroku-22 is now officially supported.
GUS-W-11298570.
> Update status of Heroku-22 based stacks in README

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
`heroku/nodejs-function`: `0.9.3 => 0.9.5`
`heroku/nodejs`: `0.5.4 => 0.5.6`
These updates are primarily s3 url changes and new node versions.
> Bump node.js buildpacks

- LICENSE
Since:
- it's the license Salesforce prefers that we use for open source projects:
https://github.com/salesforce/oss-template/blob/master/license_info.md
- it's what most of our other repositories are already using, and it would be great to be consistent
- the stack-images repo (whose images this repo build upon) is using BSD 3-Clause, so arguably this should too
- it's not that different from MIT:
https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/
All contributors to this repository so far are Salesforce employees, so there are no external code contributors from whom we need to ask permission before changing the license type.
GUS-W-11311287.
> Switch to BSD 3-Clause License

- README.md
Per:
https://devcenter.heroku.com/changelog-items/2432
GUS-W-11336640.
> Update status of Heroku-18 based images to "Deprecated"

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Upgraded `heroku/jvm-function-invoker` to `0.6.3`
* Upgrade `libcnb` to `0.8.0` and `libherokubuildpack` to `0.8.0`
* Updated `java function runtime` to `1.0.7`
* Upgraded `heroku/nodejs-function-invoker` to `0.3.2`
* Updated `nodejs function runtime` to `0.11.2`
> Bump java-function and nodejs-function

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Upgraded `heroku/nodejs-function-invoker` to `0.3.3`
* Updated `nodejs function runtime` to [v0.11.2](https://github.com/forcedotcom/sf-fx-runtime-nodejs/releases/tag/v0.11.2)
> Bump nodejs-function to 0.9.7

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings in the latest Node.js buildpacks. It includes new Node.js versions and some buildpack dependency updates.
Notable PR: https://github.com/heroku/buildpacks-nodejs/pull/297
> Bring in latest node.js buildpacks

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Default version for **OpenJDK 7** is now `1.7.0_352`
* Default version for **OpenJDK 8** is now `1.8.0_342`
* Default version for **OpenJDK 11** is now `11.0.16`
* Default version for **OpenJDK 13** is now `13.0.12`
* Default version for **OpenJDK 15** is now `15.0.8`
* Default version for **OpenJDK 17** is now `17.0.4`
* Default version for **OpenJDK 18** is now `18.0.2`
* Updated `libcnb` and `libherokubuildpack` to `0.9.0`. ([#330](https://github.com/heroku/buildpacks-nodejs/pull/330))
* Switch to the recommended regional S3 domain instead of the global one. ([#314](https://github.com/heroku/buildpacks-jvm/pull/314))
* Upgrade `libcnb` to `0.8.0` and `libherokubuildpack` to `0.8.0`.
* Upgraded `heroku/jvm` to `1.0.2`
* Upgraded `heroku/procfile` to `1.0.2`
* Upgraded `heroku/jvm` to …
> Update `heroku/jvm` to `1.0.2`

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Rollback `heroku/jvm` to `1.0.1`
> Rollback `heroku/jvm` to `1.0.1`

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Updated `libcnb` and `libherokubuildpack` to `0.9.0`. ([#481](https://github.com/heroku/libcnb.rs/pull/481) [#57](https://github.com/heroku/libherokubuildpack/pull/57))
* Switch to the recommended regional S3 domain instead of the global one. ([#314](https://github.com/heroku/buildpacks-jvm/pull/314))
* Upgrade `libcnb` to `0.8.0` and `libherokubuildpack` to `0.8.0`.
* Default version for **OpenJDK 7** is now `1.7.0_352`
* Default version for **OpenJDK 8** is now `1.8.0_342`
* Default version for **OpenJDK 11** is now `11.0.16`
* Default version for **OpenJDK 13** is now `13.0.12`
* Default version for **OpenJDK 15** is now `15.0.8`
* Default version for **OpenJDK 17** is now `17.0.4`
* Default version for **OpenJDK 18** is now `18.0.2`
* Updated `libcnb` and `libherokubuildpack` to …
> Update `heroku/jvm` to `1.0.2` and `heroku/maven` `1.0.2`

- README.md
The heroku-22 stack will soon be the default stack, suggest it.
GUS-W-11639040.
>  Update suggested stack to heroku-22

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Default version for **OpenJDK 8** is now `1.8.0_345`
* Default version for **OpenJDK 11** is now `11.0.16.1`
* Default version for **OpenJDK 17** is now `17.0.4.1`
* Upgraded `heroku/jvm` to `1.0.3`
* Upgraded `heroku/jvm` to `1.0.3`
Closes GUS-W-11665960
> Add `heroku/jvm` `1.0.3` to all builders

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Brings in the latest Node.js buildpacks. The big features here are new Node.js versions and libcnb.rs upgrades.
Relevant changelogs:
https://github.com/heroku/buildpacks-nodejs/blob/main/buildpacks/nodejs-engine/CHANGELOG.md#088-20220912
https://github.com/heroku/buildpacks-nodejs/blob/main/buildpacks/nodejs-function-invoker/CHANGELOG.md#034-20220912
> Bump Node.js CNBs

- .circleci/config.yml
The classic Java/Clojure CNB smoke tests are currently intermittently failing when trying to connect to the test app's server.
For example:
https://app.circleci.com/pipelines/github/heroku/builder/2046/workflows/d4255ddd-02cf-4fa6-b421-32e2f0cc22ba/jobs/47191
https://app.circleci.com/pipelines/github/heroku/builder/2044/workflows/54069379-9662-4bc7-b403-396799d953b2/jobs/47100
https://app.circleci.com/pipelines/github/heroku/builder/2044/workflows/54069379-9662-4bc7-b403-396799d953b2/jobs/47099
https://app.circleci.com/pipelines/github/heroku/builder/2043/workflows/6b5225ef-a290-4ddb-b53d-e7c529cc2dd2/jobs/47039
https://app.circleci.com/pipelines/github/heroku/builder/2042/workflows/ded5beb9-3e48-4101-9b5a-2da05e499dfe/jobs/47003 …
> CI: Increase retries when connecting to the test servers

- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
The previously deployed Ruby buildpack is based on the "hybrid" approach https://github.com/heroku/heroku-buildpack-ruby. Essentially Terence added support for CNB into the existing buildpack. This works, but it's not taking advantage of most of the features in CNB. It's really not too different than using the "shim" buildpack.
(The *shim* is a wrapper around any legacy/v2 buildpack that allows it to interface with CNB)
The idea is that we'll use the shim buildpack for now and switch over once a native CNB implementation in Rust is ready.
GUS-W-11461073
> Use shimmed Ruby buildpack instead of the prototype hybrid CNB

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This bumps the Java and Node.js buildpacks. The highlights include 
- https://github.com/heroku/buildpacks-nodejs/pull/352
- https://github.com/heroku/buildpacks-nodejs/pull/358
- https://github.com/heroku/buildpacks-jvm/pull/374
- https://github.com/heroku/buildpacks-jvm/pull/372
- https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/400
- https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/417
- https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/402
- https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/401
- https://github.com/forcedotcom/sf-fx-runtime-java/pull/339
- https://github.com/forcedotcom/sf-fx-runtime-java/pull/316
- https://github.com/forcedotcom/sf-fx-runtime-java/pull/314
Check the relevant changelogs for details: …
> Bump Java and Node.js buildpacks

- .github/workflows/build-test-publish.yml
The publish part of the GitHub action is not triggering (see here: https://github.com/heroku/builder/actions/runs/3176302715/jobs/5175517309). This should fix it.
Context:
https://github.com/heroku/builder/pull/286#issuecomment-1265887581
> Update publish job conditional

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Default version for **OpenJDK 8** is now `1.8.0_352`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Default version for **OpenJDK 11** is now `11.0.17`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Default version for **OpenJDK 13** is now `13.0.13`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Default version for **OpenJDK 15** is now `15.0.9`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Default version for **OpenJDK 17** is now `17.0.5`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Default version for **OpenJDK 19** is now `19.0.1`. ([#387](https://github.com/heroku/buildpacks-jvm/pull/387))
* Upgrade `libcnb` and `libherokubuildpack` to `0.11.1`. …
> JVM buildpacks updates

- .github/workflows/build-test-publish.yml
The heroku/builder-classic:22 images on Docker Hub haven't been updated since 2022-10-03: https://hub.docker.com/r/heroku/builder-classic/tags. This was the date this project cutover to GitHub Actions. 
We were using the wrong argument key for this image only.
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001BCzI3YAL/view)
> Fix publish process for heroku/builder-classic:22

- builder-22/builder.toml
- builder-classic-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Reverts #294 due to #295, which has been reported upstream at:
https://github.com/buildpacks/lifecycle/issues/945
Closes #295.
GUS-W-11995402.
> Revert "Update lifecycle from v0.14.1 to v0.15.0"

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings in the latest Node.js versions mentioned in https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/.
> Bump Node.js Buildpacks to include latest security patches

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Default version for **OpenJDK 8** is now `1.8.0_362`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Default version for **OpenJDK 11** is now `11.0.18`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Default version for **OpenJDK 13** is now `13.0.14`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Default version for **OpenJDK 15** is now `15.0.10`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Default version for **OpenJDK 17** is now `17.0.6`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Default version for **OpenJDK 19** is now `19.0.2`. ([#413](https://github.com/heroku/buildpacks-jvm/pull/413))
* Upgraded `heroku/jvm` to `1.0.6`
* Upgraded `heroku/jvm` to `1.0.6`
Ref: GUS-W-12396535
> Update default OpenJDK versions for Q1 2023 releases

- .github/workflows/build-test-publish.yml
To make debugging of any failures (particularly detect failures) easier.
> Use `--verbose` with `pack build` in CI

- .github/workflows/build-test-publish.yml
Since otherwise any other in-progress jobs get cancelled, making it hard to see whether failures in one job only affect one permutation of the matrix, or several.
See:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> Disable matrix `fail-fast` on GitHub Actions

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings in the latest Node.js buildpacks. The primary additions are:
- https://github.com/heroku/buildpacks-nodejs/pull/418
- https://github.com/heroku/buildpacks-nodejs/pull/428
- https://github.com/heroku/buildpacks-nodejs/pull/447
> Update Node.js Buildpacks

- builder-22/builder.toml
Upgrades the Go CNB to 0.1.2. This primarily includes:
- https://github.com/heroku/buildpacks-go/pull/65
- https://github.com/heroku/buildpacks-go/pull/57
> Update Go CNB to 0.1.2

- .github/workflows/build-test-publish.yml
- builder-22/builder.toml
- builder-classic-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
To pick up recent fixes/features, including an improvement to the build log output in the case where all buildpacks fail to detect. With those build log improvements the `--verbose` option to `pack build` is no longer required in CI here, and has been removed to make the rest of the logs less noisy.
This update also does bring with it a new deprecation warning for usages of old buildpack and platform API versions. These are currently triggered by buildpacks using the cnb-shim, however, they are just warnings and should be resolved separately rather than here, to avoid adding additional risk to this change.
See:
https://github.com/buildpacks/lifecycle/releases/tag/v0.16.0
https://github.com/buildpacks/lifecycle/compare/v0.15.3...v0.16.0
GUS-W-12538046.
> Update lifecycle from v0.15.3 to v0.16.0

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings the builder up to date with the latest `heroku/nodejs`, `heroku/nodejs-function`.
Primary changes are:
- Yarn 2, 3, and 4 (aka "berry") releases are now available: https://github.com/heroku/buildpacks-nodejs/blob/main/buildpacks/nodejs-yarn/CHANGELOG.md#040-20230227
- New Node.js versions: https://github.com/heroku/buildpacks-nodejs/blob/main/buildpacks/nodejs-engine/CHANGELOG.md#0816-20230227
- Buildpack API version bumps: https://github.com/heroku/buildpacks-nodejs/blob/main/meta-buildpacks/nodejs/CHANGELOG.md#060-20230227, https://github.com/heroku/buildpacks-nodejs/blob/main/meta-buildpacks/nodejs-function/CHANGELOG.md#0100-20230227
> Update Node.js CNBs

- .github/workflows/build-test-publish.yml
- README.md
- builder-22/builder.toml
The initial implementation of a native (non-[shimmed](https://github.com/heroku/cnb-shim)) [libcnb.rs](https://github.com/heroku/libcnb.rs)-based Python CNB.
Improving parity with the classic buildpack is tracked via: https://github.com/heroku/buildpacks-python/issues
The `builder:22` CI getting started matrix config has been switched from opt-in to opt-out, since more languages are now supported than unsupported.
GUS-W-12614533.
> Add heroku/python to builder:22

- .github/workflows/build-test-publish.yml
The [node-js-getting started guide](https://github.com/heroku/node-js-getting-started) should be compatible with both Node 16.x and 18.x but the Heroku-18 stack only supports Node 16.x.  This change adds an conditional step to the test workflow to downgrade the engine specified in `package.json` from `18.x || 16.x` to just `16.x`.
See:
https://github.com/heroku/node-js-getting-started/pull/294#discussion_r1127817002
GUS-W-12652981.
> Downgrade node guide test to v16 for heroku-18 stack

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
* Upgraded `heroku/jvm` to `1.0.7`
* Upgraded `heroku/jvm` to `1.0.7`
* Support for Java 20. ([#437](https://github.com/heroku/buildpacks-jvm/pull/437))
> Update `heroku/java` and `heroku/java-function`

- builder-22/builder.toml
See https://github.com/heroku/buildpacks-python/pull/26.
GUS-W-13012072.
> Update Python CNB to v0.2.0

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings in the latest language versions for Node.js and Go.
> Update heroku/go, heroku/nodejs

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Brings in node.js 18.16.0!
Changelog: https://github.com/heroku/buildpacks-nodejs/blob/main/meta-buildpacks/nodejs/CHANGELOG.md#062-20230417
> Update to latest heroku/nodejs

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This brings in the latest `heroku/nodejs-function`, which adds support for Node.js 18.16.0. This change was already applied for `heroku/nodejs` in #330.
Since `heroku/nodejs-function` and `heroku/nodejs` have different versions for `heroku/nodejs-engine` in the current release, it means multiple `heroku/nodejs-engine` buildpacks exis on the builder. This means that user's can't specify buildpacks without a version specifier. When running `pack build --buildpack heroku/nodejs-engine --builder heroku/builder:22`, there will be errors since `pack` doesn't know which `heroku/nodejs-engine` version to use.  You can see that happening here: https://github.com/heroku/buildpacks-nodejs/actions/runs/4733070280/jobs/8403481095#step:8:496. This PR should fix that issue so only one version of …
> Update heroku/node-function to 0.10.2

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This includes buildpacks updated with Node 20:
* https://github.com/heroku/buildpacks-nodejs/pull/505
* https://github.com/heroku/buildpacks-nodejs/pull/506
* https://github.com/heroku/buildpacks-nodejs/pull/507
> Updated buildpacks w/ node 20

- buildpacks-18/builder.toml
Since the `heroku/buildpacks:18` CNB builder image is based upon the Heroku-18 stack, which [has reached end-of-life](https://devcenter.heroku.com/changelog-items/2583), and as such support will soon be removed from the stack from our various buildpacks.
We will soon be stopping the publishing of `heroku/buildpacks:18` image updates entirely, however, we expect a few more upstream security updates to Ubuntu 18.04 (until 31st May, Canonical's revised EOL date) which we wish to pick up in the meantime.
By pinning the buildpack versions of our shimmed buildpacks, it unblocks removing Heroku-18 support from them in the meantime.
To pin the version, we rely on the fact that the buildpack registry stores versioned archives of each buildpack release, with a `vNNN` suffix.
However, we also have …
> Pin the buildpack versions in `heroku/buildpacks:18`

- builder-22/builder.toml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
This PR brings relevant builders up-to-date with the most recent releases of:
- heroku/nodejs
- heroku/nodejs-function
- heroku/nodejs-engine
- heroku/nodejs-yarn
- heroku/go
> Update Go and Node.js buildpacks

- .github/workflows/build-test-publish.yml
- README.md
- buildpacks-18/builder.toml
- buildpacks-18/end-of-life-buildpack/bin/build
- buildpacks-18/end-of-life-buildpack/bin/detect
- buildpacks-18/end-of-life-buildpack/buildpack.toml
The Heroku-18 stack reached end-of-life on April 30th 2023, and as of May 1st 2023, builds are no longer possible on the (default) non-CNB Heroku build system, and the underlying stack images will no longer
receive security updates (beyond whatever updates Canonical choose to
release in May). 
However, anyone using the `heroku/buildpacks:18` CNB builder image may not realise that it's now EOL and soon to be insecure. They may also not realise that the builder image has moved from the `heroku/buildpacks` Docker repo to `heroku/builder`.
In order to raise awareness of both of these, an EOL buildpack has been added, which fails the build with an EOL warning, unless the env var `ALLOW_INSECURE_HEROKU_18_BUILDER` is set to `1` during the build.
This should affect very few users, since Heroku …
> Make Heroku-18 builds fail with a skippable EOL warning

- .github/workflows/build-test-publish.yml
- buildpacks-18/builder.toml
- buildpacks-20/builder.toml
Salesforce Functions switched to using the newer `heroku/builder:22` (Heroku-22) builder image some time ago:
https://developer.salesforce.com/docs/platform/functions/guide/release-notes-intro.html#september-28-2022
As such, the Functions buildpacks in the `heroku/buildpacks:18` and `heroku/buildpacks:20` builder images are now unused.
Removing them:
- means we can reduce the size of the CI workflow for this repository down from 52 jobs to 46 jobs
- reduces the size of these legacy builder images slightly
- means the upstream buildpacks can drop support from their CI matrices too
GUS-W-13183125.
> Remove functions buildpacks from older builder images

- .github/workflows/build-test-publish.yml
* Adds an explicit name to each step, to make the jobs easier to understand
* Makes the `matrix` builder order consistent between the `create` and `test-guides` steps, so the jobs all sort in the same order in the results
* Fixes inconsistent YAML string quoting
All of these changes are a no-op in terms of actual testing/building behaviour.
I've split them out of the next PR to make that PR easier to review.
GUS-W-13196120.
> Misc GitHub Actions workflow cleanup

- .github/workflows/build-test-publish.yml
* Avoids the `docker pull` of the runtime images in the test guide/examples jobs, by saving those tags/layers in the cached image archive (which has virtually no impact on the archive size, given the layers overlap with the builder archive). (In theory the original docker pull should have been cheap, since it was performed after the builder image is imported back into the Docker daemon, but for some reason Docker was performing a full pull anyway.)
* Speeds up the cache upload/download by enabling zstd's long window mode (`--long`), which reduces the output archive size by ~20% (the only reason this isn't enabled by default, is that it requires more RAM, but that's not an issue for this use-case).
* Speeds up zstd compression by enabling multithreaded mode (`-T0`).
* Passes …
> Speed up GitHub Actions job setup/caching

- .github/workflows/build-test-publish.yml
- builder-22/builder.toml
- buildpacks-20/builder.toml
I added the new Scala buildpack to the `heroku/builder:22` only. I believe this is the strategy we had in mind when we release native CNBs to not break existing users of builders that use shimmed buildpacks.
Note: JVM buildpacks have been moved to Docker Hub.
* Upgraded `heroku/jvm` to `1.0.10`
* Upgraded `heroku/jvm` to `1.0.10`
* Upgraded `heroku/jvm-function-invoker` to `0.6.8`
* Upgrade `libcnb` and `libherokubuildpack` to `0.12.0`. ([#463](https://github.com/heroku/buildpacks-jvm/pull/463))
* The buildpack now implements Buildpack API 0.9 instead of 0.8, and so requires `lifecycle` 0.15.x or newer. ([#463](https://github.com/heroku/buildpacks-jvm/pull/463))
* Upgrade `libcnb` and `libherokubuildpack` to `0.12.0`. ([#463](https://github.com/heroku/buildpacks-jvm/pull/463))
* The …
> Update JVM buildpacks, add Scala buildpack

- .github/workflows/build-test-publish.yml
Since:
- It's not documented, or used by anything on our side.
- The `heroku/buildpacks` namespace is deprecated, so calling anything to do with it "latest" seems like it could confuse users.
- We don't publish `latest` for the new `heroku/builder` namespace either (which is probably the best decision for now, given that having such a tag means people could receive breaking changes with no notice).
I will delete the `latest` tag from Docker Hub once this is merged.
GUS-W-13213079.
> Stop publishing the `heroku/buildpacks:latest` tag

- builder-22/builder.toml
See:
https://github.com/heroku/buildpacks-python/pull/46
GUS-W-13552552.
> Update Python CNB to v0.4.0

- builder-22/builder.toml
- buildpacks-20/builder.toml
The buidpack changes include:
- New Node.js versions
- Bumps to buildpack API 0.9
- Dropped support for the deprecated `heroku-18` stack.
> Update Node.js Buildpacks to the latest versions.

- .github/workflows/build-test-publish.yml
Previously if any of the cache restore steps failed due to a timeout, the restore step would only emit a warning, such as:
```
...
Received 130023424 of 337339345 (38.5%), 1.2 MBs/sec
Warning: Failed to restore: The operation cannot be completed in timeout.
Cache not found for input keys: 5424698109-builder-classic-22
```
...and then the job would continue on to the Docker load step, which would fail with:
```
zstd: can't stat images.tar.zst : No such file or directory -- ignored
open /var/lib/docker/tmp/docker-import-4200725306/repositories: no such file or directory
Error: Process completed with exit code 1.
```
For example:
https://github.com/heroku/builder/actions/runs/5424698109/jobs/9864456202#step:5:7
Now:
* If the cache cannot be restored, the cache restore step itself will …
> Improve the UX for GHA cache restore timeout errors

- README.md
Since the `heroku/pack` Docker Hub repo has now been deleted, following a year long deprecation process.
GUS-W-13716510.
> Remove `heroku/pack` Docker repo references

- builder-22/builder.toml
See:
https://github.com/heroku/buildpacks-python/pull/79
GUS-W-13811964.
> Update Python CNB to v0.5.0

- builder-22/builder.toml
- builder-classic-22/builder.toml
- buildpacks-20/builder.toml
Of note, this adds support for Platform API 0.12 and Buildpack API 0.10 (ready for when the Heroku CNB build system and CNBs support them):
https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.12
https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.10
Release notes:
https://github.com/buildpacks/lifecycle/releases/tag/v0.16.2
https://github.com/buildpacks/lifecycle/releases/tag/v0.16.3
https://github.com/buildpacks/lifecycle/releases/tag/v0.16.4
https://github.com/buildpacks/lifecycle/releases/tag/v0.16.5
https://github.com/buildpacks/lifecycle/releases/tag/v0.17.0
Commits:
https://github.com/buildpacks/lifecycle/compare/v0.16.1...v0.17.0
GUS-W-13977966.
> Update lifecycle from v0.16.1 to v0.17.0

- .github/workflows/build-test-publish.yml
The `DYNO` env var is now set when running the built containers during this repo's integration tests. This means they more accurately reflect the Heroku environment, which is important since some of the getting started guides (eg Python's) use the presence of the `DYNO` env var to determine whether to enable production mode or not.
In the Python getting started guide, if DYNO is not set then the guide runs in debug mode, which means static assets can be dynamically fetched from the source, and so bypass the normal production assets serving mechanism. By setting `DYNO` the integration tests will now validate that the production assets have been generated (via the `manage.py collectstatic` command that is now automatically run by the Python CNB).
GUS-W-14144906.
> Set the `DYNO` env var when running integration tests

- builder-22/builder.toml
- builder-classic-22/builder.toml
- buildpacks-20/builder.toml
In upcoming PRs I'll be adding new image variants. Sorting the list of buildpacks/URIs will make it easier to diff the included buildpacks in each builder.
This change is a no-op for the created builder itself - the detection `[[order]]` has remained unchanged.
> Sort `[[buildpacks]]` alphabetically

- builder-22/builder.toml
- builder-classic-22/builder.toml
- buildpacks-20/builder.toml
https://github.com/buildpacks/lifecycle/releases/tag/v0.17.1
https://github.com/buildpacks/lifecycle/compare/v0.17.0...v0.17.1
GUS-W-14178768.
> Update lifecycle from v0.17.0 to v0.17.1

- .github/workflows/build-test-publish.yml
Setting an explicit bash shell ensures GitHub Actions enables pipefail mode too, rather than only error on exit (due to GitHub Actions slightly counter-intuitive choice of settings):
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
This is important for UX since this workflow uses pipes.
For example, without this change, if the `docker save` command here fails, then the piping to zstd otherwise continues, resulting in an empty exported images archive that will only fail much later in the build when the archive is `docker load`ed:
https://github.com/heroku/builder/actions/runs/6303703122/job/17113579563?pr=392#step:5:7
This shell is set globally, to avoid needing to specify it for every job or run command: …
> Set an explicit GitHub Actions shell

- .github/workflows/build-test-publish.yml
- Makefile
- salesforce-functions/builder.toml
We want to move Salesforce Functions buildpacks to their own builder image variant to more cleanly separate the two use cases (particularly given that Salesforce Functions is now deprecated), and prevent a number of issues (such as builds on the functions build system being able to pass detection even when the match against a non-functions buildpack).
For more details, see:
https://salesforce.quip.com/MoDFAX3MEf8b
The first stage of this is to create the new builder image variant.
This new variant is only being published to the internal private registry, since it's only being used by Kodon (the SF CLI no longer supports using containers to run functions) so doesn't need to be available on Docker Hub.
Once it's released, we can then switch Kodon to using the new tag, deploy Kodon to all …
> Add a Salesforce Functions builder variant

- .github/workflows/build-test-publish.yml
- Makefile
- README.md
- builder-20/builder.toml
The builder images in this repository fall into two main groups:
1. The legacy `heroku/buildpacks:*` builder namespace that use a mixture of native CNBs and shimmed classic buildpacks.
2. The newer `heroku/builder:*` builder namespace that uses only native (non-shimmed) CNBs.
Previously, if someone wanted to use the newer builder image type they had to use `heroku/builder:22` which is based on the Heroku-22 stack (Ubuntu 22.04). 
Now, if someone needs to use Heroku-20  (Ubuntu 20.04), they can do so via a new `heroku/builder:20` image, rather than needing to fall back to the older `heroku/buildpacks:20` image and its shimmed classic buildpacks.
This will make it easier for us to deprecate `heroku/buildpacks:20` in future PRs, since there will now be an easier upgrade paths for users that …
> Add `heroku/builder:20`

- .github/workflows/update-lifecycle.yml
Previously we had to manually keep track of [upstream lifecycle releases](https://github.com/buildpacks/lifecycle/releases), and then open PRs to update the builder manifest for each builder with the new version. 
For example:
https://github.com/heroku/cnb-builder-images/pull/389
Now, every Monday at 8am UTC, a GitHub Actions job will check for updates, and open a PR if the latest lifecycle version is newer than that used by the `heroku/builder:22` builder. (This means lifecycle version pinning will be supported too for eg our legacy images, since only builder images on the latest version will end up being updated each time.)
This new workflow can also be triggered manually thanks to the `workflow_dispatch` annotation.
GUS-W-14329446.
> Add automation for updating builder lifecycle version

- .github/workflows/update-lifecycle.yml
Sets `GH_TOKEN` when calling `gh release view`, otherwise it returns an empty payload (but still exits zero, sigh).
Also adjusts the PR creation step name to make it clearer that PRs are also updated too.
GUS-W-14329446.
> Fix automation for updating builder lifecycle version

- builder-classic-22/builder.toml
- buildpacks-20/builder.toml
So that:
- The naming style matches that chosen in #408
- It's clearer that these are shimmed buildpacks and not the native CNB versions of the buildpacks with the same name
I've inspected the contents of the generated archives to ensure that the URL unescaping works as expected.
GUS-W-14121598.
> Update display name of shimmed buildpacks

- .github/workflows/build-test-publish.yml
Since:
- This guide isn't used by any Dev Center documentation: https://devcenter.heroku.com/search?q=typescript
- It's outdated (no updates for two years).
- TypeScript apps use the same `heroku/nodejs` CNB as JavaScript apps, and `heroku/nodejs` is already tested via the main Node.js getting started guide.
- The CI for this repo doesn't test multiple guides for any of the other supported languages.
- Removing it unblocks #417 (since the TypeScript guide is missing an NPM lockfile).
See also:
https://github.com/heroku/cnb-builder-images/pull/417#issuecomment-1779222791
GUS-W-14364069.
> Stop testing against the TypeScript getting started guide

- .github/workflows/build-test-publish.yml
* Adds retry/timeout/displaying-errors best practices to the Curl usage
* Adds `--exit-status` to the jq usage
* Splits the combined public and private publishing step into two, to make it easier to follow the process/logs and allow for measuring how long each is taking separately (for example, the private publish appears to be currently pushing even for unchanged images that should be no-op?)
* Various other bash cleanups, such as proper variable quoting.
GUS-W-14371285.
> Clean up the GitHub Actions publishing job

- .github/workflows/build-test-publish.yml
The `heroku/buildpacks:20` and `heroku/builder:22` builders are now only published to Docker Hub, rather than also being published to the internal registry (where they were tagged as `heroku-20:builder` and `heroku-22:builder` respectively).
Kodon has not defaulted to these non-functions images from the internal registry for some time, and as of heroku/kodon#410 these images (and the internal registry) are no longer on the builder allow list, so it's not possible to manually select them using `project.toml`.
This change does not affect the functions-only image, which continues to be published to (and consumed by the functions-specific Kodon instance from) the internal registry.
GUS-W-14378185.
> Stop publishing non-functions images to the internal registry

- README.md
- builder-classic-22/builder.toml
- builder-classic-22/end-of-life-buildpack/bin/build
- builder-classic-22/end-of-life-buildpack/bin/detect
- builder-classic-22/end-of-life-buildpack/buildpack.toml
- buildpacks-20/builder.toml
- buildpacks-20/end-of-life-buildpack/bin/build
- buildpacks-20/end-of-life-buildpack/bin/detect
- buildpacks-20/end-of-life-buildpack/buildpack.toml
Adds deprecation warnings to the `heroku/builder-classic:22` and `heroku/buildpacks:20` CNB builder images, to raise awareness that they are no longer supported/recommended.
The warnings have been added using a warnings buildpack, similar to the approach used for the Heroku-18 EOL in:
https://github.com/heroku/cnb-builder-images/pull/336
For now these are just warnings, however, in the future will be changed to an error (skippable via env var, like in the PR linked above).
Since these are warnings, the buildpack has been added to the end of each buildpack order group, such that the message is at the end of the overall build log, and so hopefully more visible to end users. (Once the warning is turned into an error, the buildpack should be moved to the start of the order groups, so the …
> Add deprecation warnings to legacy builder images

- builder-classic-22/end-of-life-buildpack/buildpack.toml
- buildpacks-20/end-of-life-buildpack/buildpack.toml
Amongst other reasons, this now means that `pack builder inspect` will no longer be missing the name/URL for the EOL buildpack.
Before:
```
Buildpacks:
ID                                NAME                            VERSION        HOMEPAGE
heroku/builder-eol-warning        -                               1.0.0          -
...
```
After:
```
Buildpacks:
ID                                NAME                               VERSION        HOMEPAGE
heroku/builder-eol-warning        Builder End-of-Life Warning        1.0.0          https://github.com/heroku/cnb-builder-images
...
```
Follow-up to #429.
GUS-W-14547289.
> Add name, homepage and license to EOL buildpacks metadata

- .github/workflows/update-lifecycle.yml
- README.md
- builder-20/builder.toml
- builder-22/builder.toml
- builder-classic-22/builder.toml
- builder-classic-22/end-of-life-buildpack/bin/build
- buildpacks-20/builder.toml
- buildpacks-20/end-of-life-buildpack/bin/build
- salesforce-functions/builder.toml
The repo README has been overhauled, to:
- Give more context as to what a builder is, and link to the upstream docs.
- Emphasise that these images are experimental and not yet used for "normal" Heroku builds.
- Make it easier to understand the difference between the image variants, including attributes such as run image and lifecycle version.
- Make the usage instructions more accessible for beginners.
- Give users breadcrumbs to follow when trying to work out where to file issues.
The "update lifecycle" GitHub Actions workflow has been modified so that it now also modifies the lifecycle version in the README in addition to that in the builder manifests.
Lastly, the description metadata used for each builder (that is shown by `pack builder inspect`) has also been updated to mention …
> Improve documentation and description metadata

- README.md
This is part of the [Rename stack image to base image](https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QEE000000jgBB2AY/view) epic.
> The Heroku term "stack" is overloaded. To reduce confusion, we will rename "stack image" to "base image".
[W-14866121](https://gus.lightning.force.com/lightning/r/a07EE00001ie1mxYAA/view)
> Use "base image" terminology

- .github/workflows/build-test-publish.yml
As of Pack 0.33.0 (which this repo is using thanks to #462), there is a new `--force-color` argument that makes `pack build` output logs in colour even if a TTY wasn't detected (as is the case on GHA):
https://github.com/buildpacks/pack/releases/tag/v0.33.0
This will allow us to see the colour output from the new build output implementation.
GUS-W-14968745.
> Use `--force-color` with `pack build` invocations

- README.md
- builder-20/builder.toml
- builder-22/builder.toml
This updates the builder images to the latest lifecycle version, `0.19.0-rc.2`, Which includes a fix to https://github.com/buildpacks/lifecycle/issues/1308. 
Internal conversation about this issue: https://salesforce-internal.slack.com/archives/C01R6FJ738U/p1709318630497849.
> Update lifecycle from v0.18.5 to v0.19.0-rc.2

- builder-classic-22/end-of-life-buildpack/bin/build
- buildpacks-20/end-of-life-buildpack/bin/build
Previously the colourisation of the deprecation messages would break if the output had prefixes added later (for example as happens when using an untrusted builder).
Now, each line is wrapped in its own colour code + reset code, which resolves the issue.
GUS-W-15212105.
> Fix ANSI escape code wrapping of deprecation messages

- .github/workflows/build-test-publish.yml
The latest version of Pack CLI (v0.33.2) supports Platform API <= 0.12:
https://github.com/buildpacks/pack/blob/v0.33.2/internal/build/lifecycle_executor.go#L34
This means when it's used with any lifecycle version newer than 0.17.x, a `pack build` will end up using Platform API 0.12:
https://github.com/buildpacks/lifecycle#supported-apis
Therefore all of our tests in our CNB repos, and the smoke tests in this repo are all testing against Platform API 0.12.
However, Kodon is currently using Platform API 0.9, and whilst this is in the process of being upgraded (GUS-W-15122354), it's unlikely that the version will be upgraded for Kodon's `functions_eol` branch:
https://github.com/heroku/kodon/blob/functions_eol/internal/constants/constants.go#L75
As such, I've updated the functions tests …
> Use older Pack CLI / Platform API for Functions tests

- README.md
The `heroku/procfile` CNB GitHub repo has been renamed to:
https://github.com/heroku/buildpacks-procfile
> Update Procfile CNB GitHub repo URL

- README.md
- builder-classic-22/builder.toml
- buildpacks-20/builder.toml
- salesforce-functions/builder.toml
To pick up this backported fix:
https://github.com/buildpacks/lifecycle/pull/1317
...so that the legacy builder images still work when we have the next base image release - which will include this removal of the `CNB_TARGET_*` env vars workaround:
https://github.com/heroku/base-images/pull/260
Release notes:
https://github.com/buildpacks/lifecycle/releases/tag/v0.17.5
Full changelog:
https://github.com/buildpacks/lifecycle/compare/v0.17.4...v0.17.5
GUS-W-15225541.
> Update lifecycle in legacy builders from v0.17.4 to v0.17.5

- .github/workflows/build-test-publish.yml
- README.md
- builder-classic-22/builder.toml
- builder-classic-22/end-of-life-buildpack/bin/build
- builder-classic-22/end-of-life-buildpack/buildpack.toml
- buildpacks-20/builder.toml
- buildpacks-20/end-of-life-buildpack/bin/build
- buildpacks-20/end-of-life-buildpack/buildpack.toml
This upgrades the deprecation warnings added in #429 to errors, for the reasons mentioned in #474. It uses an approach similar to that used for the Heroku-18 EOL in #336.
These errors can be skipped by setting the env var: `ALLOW_EOL_SHIMMED_BUILDER=1`
For example:
`pack build --env ALLOW_EOL_SHIMMED_BUILDER=1 ...`
However, users are strongly encouraged to migrate from the legacy shimmed `heroku/buildpacks:20` and `heroku/builder-classic:22` images to the new `heroku/builder:*` builder images.
For the differences between the available images, see:
https://github.com/heroku/cnb-builder-images#available-images
The buildpack has also been moved to the start of each `[[order]]` group (rather than the end), so that the build fails early, rather than wasting the user/build system's time with a …
> Upgrade legacy builder deprecation warnings to errors

- salesforce-functions/builder.toml
The Bash based NPM buildpack is no longer using one of the unsupported Buildpack API versions as of:
https://github.com/heroku/buildpacks-nodejs/pull/721
As such, the comment in the functions builder about why an older `lifecycle` version is being used can be updated to reference only the custom buildpacks reason instead.
> Update explanation of why older lifecycle is used in functions builder

- builder-classic-22/end-of-life-buildpack/bin/build
- buildpacks-20/end-of-life-buildpack/bin/build
Updates the EOL message to reflect that we're now stopping updating these images. I've also removed the explicit builder image name example from the message, since it will get out of date once future builders are released.
The messaging has to be updated in this separate PR first, so we can do one more release with the new messaging before removing the publishing jobs in the next PR.
Towards #512.
> Update EOL message shown for legacy builders

- .github/workflows/build-test-publish.yml
Now that we build/test ARM64 images too, the job names shown in the GitHub Actions UI have become quite hard to read.
This adjust the job names and matrix parameter order (which determines the order in which parameters appear in the auto-generated job names) to make them easier to read in the UI.
In addition, the Heroku-24 test entries have been changed to use `exclude` rather than `include` to reduce the amount of boilerplate, and also mean the jobs display in the correct sequence in the UI.
> Cleanup workflow job definitions

- README.md
- builder-20/builder.toml
- builder-22/builder.toml
- builder-24/builder.toml
Now that the PHP CNB supports Heroku-24 (incl ARM64) and has been added to `heroku/builder:24`, it means the `heroku/builder:24` builder is now complete (or at least as complete as our other builder images).
As such, we can:
- update the descriptions to mention it supports all languages
- mark `heroku/builder:24` as recommended and use it in the example usage instructions
I also spotted a few other small improvements that could be made to the README.
GUS-W-14686693.
GUS-W-14688185.
> Update status of `heroku/builder:24`

- README.md
- builder-20/builder.toml
Per:
https://devcenter.heroku.com/changelog-items/2895
GUS-W-14701074.
> Mark `heroku/builder:20` as deprecated

- .github/workflows/update-lifecycle.yml
The use-app-token action is deprecated: https://github.com/heroku/use-app-token-action/pull/17
GUS-W-16159717
> Use actions/create-github-app-token instead of heroku/use-app-token

- builder-20/builder.toml
- builder-20/eol-buildpack/bin/build
- builder-20/eol-buildpack/bin/detect
- builder-20/eol-buildpack/buildpack.toml
This adds a deprecation message to all builds using `heroku/builder:20`. 
Since this builder is based on the now deprecated `heroku/heroku:20` ([changelog entry](https://devcenter.heroku.com/changelog-items/2895)), security updates for `heroku/builder:20` will stop April 30, 2025. This messaging should encourage folks to update to a newer builder so that they may keep getting security updates and avoid interruption.
Example pack output:
[heroku-20 EOL plan]( https://salesforce.quip.com/ss13A0jDWb7a)
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001gotTdYAI/view)
> Add deprecation messaging to builder:20

- builder-20/eol-buildpack/bin/build
`s/bulder/builder/`
Follow-up to #552.
> Fix typo in `heroku/builder:20` deprecation message

- .github/workflows/build-test-publish.yml
This PR changes the publish automation to additionally push builder images to `public.ecr.aws/heroku/builder`. This aims to alleviate some Docker Hub rate limit concerns and enables faster downloads in some cloud environments. The primary and canonical location for these images is still `heroku/builder` (on dockerhub).
This automation makes use of GitHub OIDC to authenticate with AWS so no IAM users or access tokens are in use.
[GUS](https://gus.lightning.force.com/a07EE00001qVbCRYA0)
> Copy builder images to public ecr

- builder-20/builder.toml
- builder-22/builder.toml
- builder-24/builder.toml
This PR updates our build/run image configuration for builders by:
1. Referencing the new `public.ecr.aws/heroku/heroku` tags as mirrors
2. Adding explicit `docker.io` domains to the Docker Hub hosted tags (for explicitness and differentiation from the ECR mirrors)
3. Adding the new-ish builder.toml `build` and `run` keys outlined [here]( https://github.com/buildpacks/spec/pull/363/files#diff-83b8682bde66aedd4caaef8d64467832f54d7bf053c51b51dd77c9620c1beae6R221-R238). With this PR, we support both `stacks` (platform API 0.11 and older) and `build` + `run` keys (platform API 0.12 and newer).
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001xkt9VYAQ/view)
> Specify run image mirrorrs

- builder-22/builder.toml
- builder-24/builder.toml
Registers the [heroku/deb-packages buildpack](https://github.com/heroku/buildpacks-deb-packages) in the following builders, prepending it to each buildpack group as an optional buildpack that runs at the start for:
- `heroku/builder:24`
- `heroku/builder:22`
> [!note]
> This will not be added to `heroku/builder:20` as that builder is deprecated.
GUS-W-17066441.
> Add `heroku/deb-packages` to 22/24 builders

- builder-20/builder.toml
- builder-22/builder.toml
- builder-24/builder.toml
Apps written in other languages often have a `package.json`, and the current order causes these to be detected as a Node.js codebase.
N.b. the diff for `heroku-20` is just a bit funky looking, it's really the same as for the two others when you look at it with `git diff --patience`:
```diff
diff --git a/builder-20/builder.toml b/builder-20/builder.toml
index 097d01f..c09b53c 100644
--- a/builder-20/builder.toml
+++ b/builder-20/builder.toml
@@ -89,18 +89,6 @@ version = "0.20.1"
id = "heroku/eol-warning"
version = "1.0.0"
-[[order]]
-  [[order.group]]
-    id = "heroku/nodejs"
-    version = "3.2.13"
-  [[order.group]]
-    id = "heroku/procfile"
-    version = "3.1.2"
-    optional = true
-  [[order.group]]
-    id = "heroku/eol-warning"
-    version = "1.0.0"
-
[[order]]
[[order.group]] …
```
> Move heroku/nodejs group to the end

- .github/dependabot.yml
- .github/workflows/build-test-publish.yml
- .github/workflows/update-lifecycle.yml
The full-version Git tags used by Actions are mutable (as seen in recent events in the wider GitHub Actions community), so pinning third-party Actions to a SHA is recommended:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
The version tag has been added after the pin as a comment (as a readability aid) in a format that Dependabot will keep up to date: https://github.com/dependabot/dependabot-core/issues/4691
I've also enabled Dependabot grouping for GitHub Actions updates to reduce PR noise.
GUS-W-18051077.
> Pin SHA of third-party GitHub Actions

- .github/workflows/build-test-publish.yml
Since this env var was added in #385 primarily for the Python Getting Started Guide, but that guide:
- No longer requires that the env var be set in order to run in production mode, as of:
https://github.com/heroku/python-getting-started/pull/251
- Now redirects to HTTPS if `DYNO` is set (which is not what we want for these tests, since there is no TLS cert configured), as of:
https://github.com/heroku/python-getting-started/pull/253
Also, we're about to add Direwolf tests for CNBs/Fir, which will test the guides in a true Heroku-like setting, so it makes more sense for these smoke tests to more accurately test the local `pack build` workflow instead - rather than a hybrid of both.
Lastly, I've added `-L` to the curl usages (which makes it follow redirects), so that any issues with …
> Stop setting `DYNO` when running the test apps in CI

- .github/workflows/build-test-publish.yml
- README.md
- builder-20/builder.toml
- builder-20/eol-buildpack/bin/build
- builder-20/eol-buildpack/buildpack.toml
Heroku-20, Heroku's Ubuntu 20.04 based stack, was previously deprecated in June 2024:
https://devcenter.heroku.com/changelog-items/2895
The `heroku/builder:20` image has been outputting deprecation warnings since July 2024:
https://github.com/heroku/cnb-builder-images/pull/552
Now, in accordance with our stack support policy and the documented EOL timelines, the stack and thus the builder image have reached end-of-life.
As such, the EOL warnings have been upgraded to errors (which can be bypassed by setting an env var), similar to what we did for the legacy builder image sunset in #478.
Users who want to continue to use this builder, will need to set the env var:
`ALLOW_EOL_HEROKU_BUILDER_20=1`
The EOL warning buildpack has been moved first in the group detection order, so that builds …
> Upgrade the `heroku/builder:20` deprecation warning to an error

- README.md
- builder-22/builder.toml
- builder-24/builder.toml
(I'm opening a manual PR for this, since the GHA workflow doesn't support updating to releases still listed as pre-release)
Release notes:
https://github.com/buildpacks/lifecycle/releases/tag/v0.20.13
Full changelog:
https://github.com/buildpacks/lifecycle/compare/v0.20.12...v0.20.13
Also corrects the lifecycle version listed in README for `heroku/builder:20`, which is no longer updated.
GUS-W-19336168.
> Update lifecycle from v0.20.12 to v0.20.13
